---
base_system_enable_rpm_fusion: true
base_system_enable_keyd_copr: false
base_system_enable_keyd_src: true
base_system_keyd_version: v2.5.0
base_system_update: true
base_system_enable_flathub: true
base_system_enable_gnome_sound: true
base_system_enable_speaker_sound: true
base_system_enable_proton_vpn: true
base_system_enable_1password: true
base_system_enable_brave_browser_beta: true
base_system_enable_gh_cli: true
base_system_enable_fedora_cisco_openh264: true
base_system_enable_nvidia: true


# Backup configuration variables
base_system_enable_backup: true
base_system_backup_paths: "/home"
base_system_borg_compression: "zlib,6"
base_system_keep_hourly: "24"
base_system_keep_daily: "7"
base_system_keep_weekly: "4"
base_system_keep_monthly: "3"
base_system_borg_prefix_repo: "/var/local/backup/"
base_system_borg_passphrase_file: "/etc/backup/passphrase"
base_system_backup_nice_value: "10"
base_system_backup_timeout_start: "50m"
base_system_backup_timer_interval: "hourly"
base_system_backup_random_delay: "15m"

base_system_packages:
  - dnf-utils
  - emacs
  - htop
  - rsync
  - net-tools
  - bind-utils
  - traceroute
  - plocate
  - tmux
  - fwupd

base_desktop_packages:
  - brave
  - emacs
  - terminator
  - ulauncher

base_system_hostname: "{{ lookup('env', 'HOSTNAME_PREFIX') }}"
base_system_domain: "{{ lookup('env', 'DOMAIN')}}"

base_system_chrony_servers:
  - "192.168.10.1 iburst"
  - "0.fedora.pool.ntp.org iburst"
  - "1.fedora.pool.ntp.org iburst"
  - "2.fedora.pool.ntp.org iburst"
  - "3.fedora.pool.ntp.org iburst"

base_system_selinux_mode: "enforcing"

base_system_default_user: "{{ lookup('env', 'DEFAULT_USER') }}"
base_system_default_user_groups:
  - wheel
  - "{{ lookup('env', 'ADDITIONAL_GROUP') | default('user', true) }}"

base_system_disable_filesystems:
  - cramfs
  - udf

base_system_sysctl_settings:
  net.ipv4.conf.all.log_martians: 1
  net.ipv4.conf.default.log_martians: 1

