---
base_system_enable_rpm_fusion: true
base_system_enable_keyd_copr: false
base_system_enable_keyd_src: true
base_system_keyd_version: v2.5.0
base_system_update: true
base_system_enable_flathub: true
base_system_enable_gnome_sound: true
base_system_enable_speaker_sound: true
base_system_enable_proton_vpn: true
base_system_enable_1password: true
base_system_enable_brave_browser_beta: true
base_system_enable_gh_cli: true
base_system_enable_fedora_cisco_openh264: true
base_system_enable_nvidia: true
base_system_enable_nvidia_multi_device: false

# Backup configuration variables
base_system_enable_backup: true
base_system_backup_paths: "/home"
base_system_borg_compression: "zlib,6"
base_system_keep_hourly: "24"
base_system_keep_daily: "7"
base_system_keep_weekly: "4"
base_system_keep_monthly: "3"
base_system_borg_prefix_repo: "/var/local/backup/"
base_system_borg_passphrase_file: "/etc/backup/passphrase"
base_system_backup_nice_value: "10"
base_system_backup_timeout_start: "50m"
base_system_backup_timer_interval: "hourly"
base_system_backup_random_delay: "15m"

# Virus Scan configuration variables
base_system_enable_clamav_clamscan: false
base_system_enable_clamav_clamonacc: false
base_system_enable_clamav_freshclam: false

base_system_clamav_scan_on_access: yes
base_system_clamav_on_access_prevention: no
base_system_clamav_on_access_disable_ddd: no
base_system_clamav_on_access_exclude_root_uid: yes
base_system_clamav_supgroup: "virusgroup"

base_system_clamav_scan_dirs:
  - /home
  - /var/tmp
  - /tmp
  - /run/user
  - /mnt
  - /media

base_system_clamav_test_dbs: "yes"
base_system_clamav_db_mirror: "database.clamav.net"
base_system_clamd_tmp_dir: /run/clamd/tmp/
base_system_clamd_user: clamscan
base_system_clamd_pid_file: /run/clamd/clamd.pid
base_system_clamd_limit_nofile: 65535
base_system_clamd_limit_nproc: 65535
base_system_clamd_local_socket: /run/clamd/clamd.sock
base_system_clamd_local_socket_mode: "760"
base_system_clamd_on_access_include_path: /home
base_system_clamd_on_access_mount_path: /
base_system_clamd_max_threads: 13
base_system_clamd_max_file_size: 4096M
base_system_clamd_max_file_size_exceeded: log
base_system_clamd_max_dir_recursion: 20
base_system_clamd_scan_archive: "yes"
base_system_clamd_on_access_max_threads: 4
base_system_clamd_virus_event: /usr/local/sbin/clamv-event.sh
base_system_clamd_exclude_path_dev: "^/dev/"
base_system_clamd_exclude_path_proc: "^/proc/"
base_system_clamd_exclude_path_sys: "^/sys/"
base_system_clamd_extended_detection_info: "yes"
base_system_clamscan_on_boot_sec: 5min
base_system_clamscan_on_calendar: "*-*-* 00,06,12,18:10:00"
base_system_clamscan_randomized_delay_sec: 10min
base_system_clamscan_options: "--verbose"
base_system_clamav_freshclam_conf_path: /etc/freshclam.conf
base_system_clamd_conf_path: /etc/clamd.d/%i.conf
base_system_clamav_freshclam_on_calendar: "*-*-* 00,06,12,18:00:00"
base_system_clamav_freshclam_randomize_delay_sec: 5m
base_system_clamd_timeout_start_sec: 420

base_system_packages:
  - dnf-utils
  - emacs
  - htop
  - rsync
  - net-tools
  - bind-utils
  - traceroute
  - plocate
  - tmux
  - fwupd
  - setroubleshoot-server

base_desktop_packages:
  - brave
  - emacs
  - terminator
  - ulauncher

base_system_hostname: "{{ lookup('env', 'HOSTNAME_PREFIX') }}"
base_system_domain: "{{ lookup('env', 'DOMAIN')}}"

base_system_chrony_servers:
  - "192.168.10.1 iburst"
  - "0.fedora.pool.ntp.org iburst"
  - "1.fedora.pool.ntp.org iburst"
  - "2.fedora.pool.ntp.org iburst"
  - "3.fedora.pool.ntp.org iburst"

base_system_selinux_mode: "enforcing"

base_system_default_user: "{{ lookup('env', 'DEFAULT_USER') }}"
base_system_default_user_groups:
  - wheel
  - "{{ lookup('env', 'ADDITIONAL_GROUP') | default('user', true) }}"

base_system_disable_filesystems:
  - cramfs
  - udf

base_system_sysctl_settings:
  net.ipv4.conf.all.log_martians: 1
  net.ipv4.conf.default.log_martians: 1
