---
all:
  vars:
    env_name: "stage"
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('ansible', true) }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY') | default('~/.ssh/id_rsa', true) }}"
    base_system_hostname: "{{ lookup('env', 'HOSTNAME_PREFIX') | default('stage-penguin', true) }}"
    base_system_domain: "{{ lookup('env', 'DOMAIN') | default('lan', true) }}"
    base_system_default_user: "{{ lookup('env', 'DEFAULT_USER') | default('foo', true) }}"
    base_system_default_user_groups:
      - wheel
      - "{{ lookup('env', 'ADDITIONAL_GROUP') | default('users', true) }}"

  children:
    workstations:
      hosts:
        workstation-stage:
          ansible_host: "{{ lookup('env', 'STAGE_WORKSTATION_IP') }}"

    servers:
      hosts:
        server-stage:
          ansible_host: "{{ lookup('env', 'STAGE_SERVER_IP') }}"
