---
all:
  vars:
    env_name: "dev"
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('ansible', true) }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY') | default('~/.ssh/id_rsa', true) }}"
    base_system_hostname: "{{ lookup('env', 'HOSTNAME_PREFIX') | default('dev-penguin', true) }}"
    base_system_domain: "{{ lookup('env', 'DOMAIN') | default('lan', true) }}"
    base_system_default_user: "{{ lookup('env', 'DEFAULT_USER') | default('foo', true) }}"
    base_system_default_user_groups:
      - wheel
      - "{{ lookup('env', 'ADDITIONAL_GROUP') | default('users', true) }}"

  children:
    workstations:
      hosts:
        workstation-dev:
          ansible_connection: local
          base_system_hostname: "{{ lookup('env', 'WORKSTATION_HOSTNAME_PREFIX') | default('workstation', true) }}"
          ansible_host: "{{ lookup('env', 'DEV_WORKSTATION_IP') | default('127.0.0.1', true) }}"

    servers:
      hosts:
        server-dev:
          base_system_hostname: "{{ lookup('env', 'SERVER_HOSTNAME_PREFIX') | default('workstation', true) }}"
          ansible_host: "{{ lookup('env', 'DEV_SERVER_IP') | default('127.0.0.2', true) }}"
