---
- name: Disable mounting of specified filesystems
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "install {{ item }} /bin/true"
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'
  loop: "{{ base_system_disable_filesystems }}"

- name: Configure mount options for /tmp
  ansible.builtin.mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,nodev,nosuid,noexec
    state: mounted

- name: Configure mount options for /var/tmp
  ansible.builtin.mount:
    path: /var/tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,nodev,nosuid,noexec
    state: mounted

- name: Configure mount options for /home (Btrfs Subvolume)
  ansible.builtin.mount:
    path: /home
    src: "{{ ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='device') | first | default(omit) }}"
    fstype: btrfs
    opts: "defaults,nodev,nosuid,subvol={{ btrfs_home_subvolume_name }}"
    state: mounted
  when:
    - ansible_mounts | selectattr('mount', 'equalto', '/home') | list | count > 0
    - "'btrfs' in ansible_mounts | selectattr('mount', 'equalto', '/home') | map(attribute='fstype') | first | default('')"
  vars:
    btrfs_home_subvolume_name: home
