---
- name: Disable mounting of specified filesystems
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "install {{ item }} /bin/true"
    state: present
    create: true
    owner: root
    group: root
    mode: '0644'
  loop: "{{ base_system_disable_filesystems }}"

- name: Configure mount options for /tmp
  ansible.builtin.mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,nodev,nosuid,noexec
    state: mounted

- name: Configure mount options for /var/tmp
  ansible.builtin.mount:
    path: /var/tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,nodev,nosuid,noexec
    state: mounted

- name: Configure mount options for /home
  ansible.builtin.mount:
    path: /home
    src: "{{ ansible_mounts | selectattr('mount', 'equalto', '/home') | map(attribute='device') | first | default(omit) }}"
    fstype: "{{ ansible_mounts | selectattr('mount', 'equalto', '/home') | map(attribute='fstype') | first | default(omit) }}"
    opts: defaults,nodev,nosuid
    state: mounted
  when: ansible_mounts | selectattr('mount', 'equalto', '/home') | list | count > 0
