---
- name: Install systemd-resolved
  ansible.builtin.dnf:
    name: systemd-resolved
    state: present

- name: Create systemd resolved.conf.d
  ansible.builtin.file:
    name: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: 755

- name: Configure DNS options
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/dns.conf
    content: |
      [Resolve]
      DNSSEC=allow-downgrade
      DNSOverTLS=opportunistic
      MulticastDNS=yes
      Cache=yes
      LLMNR=no
      DNSStubListener=yes
      ReadEtcHosts=yes
    owner: root
    group: root
    mode: '0644'
  register: dns_options

- name: Enable and start systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
    enabled: true
  when: dns_options.changed
