---
- name: Install RPM Fusion repositories
  ansible.builtin.dnf:
    name:
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
    state: present
  when: base_system_enable_rpm_fusion | bool

- name: Configure DNF for faster downloads
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    no_extra_spaces: true
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { option: 'fastestmirror', value: 'true' }
    - { option: 'max_parallel_downloads', value: '10' }
    - { option: 'deltarpm', value: 'true' }

- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ base_system_packages }}"
    state: present
    update_cache: true

- name: Install COPR tools
  ansible.builtin.dnf:
    name: 'dnf-plugins-core'
    state: present

- name: Enable keyd COPR repository
  ansible.builtin.command:
    cmd: dnf copr enable -y alternateved/keyd
  register: copr_result
  changed_when: false
  when: base_system_enable_keyd_copr | bool

- name: Install keyd package
  ansible.builtin.dnf:
    name: keyd
    state: present
  when: base_system_enable_keyd_copr | bool

  # Enable keyd service
- name: Enabled keyd service
  ansible.builtin.systemd:
    name: keyd
    enabled: true
    state: started
  when: base_system_enable_keyd_copr | bool
