---
- name: Install chrony package
  ansible.builtin.dnf:
    name: chrony
    state: present

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart chrony service

- name: Enable and start chrony service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
