---
- name: Create default user
  ansible.builtin.user:
    name: "{{ base_system_default_user }}"
    groups: "{{ base_system_default_user_groups }}"
    append: true
    state: present
    create_home: true
    shell: /bin/bash
  when: base_system_default_user_groups is not none

- name: Configure sudo access for default user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/custom
    line: "{{ base_system_default_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    create: true
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'
  when: base_system_default_user_groups is not none
