---
role_name_check: 1
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
  options:
    managed: false
platforms:
  - name: test-vm
    instance_name: bwf-test-${MOLECULE_SCENARIO_NAME:-default}
    groups:
      - molecule
    memory: 4096
    cpus: 4
    connection: ssh
    ansible_connection: ssh
    ansible_user: molecule
    ansible_host: 127.0.0.1
    ansible_port: 2222
    ansible_private_key_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-${USER}/tmp
      vault_password_file: ~/.vault-pass
  env:
    ANSIBLE_ROLES_PATH: ../../../
    DEFAULT_USER: molecule-user
    HOSTNAME_PREFIX: molecule-test
    DOMAIN: lan
  inventory:
    host_vars:
      test-vm:
        ansible_host: 127.0.0.1
        ansible_port: 2222
        ansible_user: molecule
        ansible_private_key_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
        ansible_become: true
        base_system_update: false
        base_system_enable_flathub: true
        molecule_test: true
        is_workstation: true
verifier:
  name: testinfra
  directory: ../tests
  options:
    v: true
    s: true
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
