---
- name: Prepare the VM for testing
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install python3
      ansible.builtin.raw: dnf install -y python3 python3-dnf python3-libdnf5
      changed_when: false

    - name: Ensure Python is available for Ansible
      ansible.builtin.package:
        name: python3
        state: present

    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
