---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Notify that we are using testinfra to test
      ansible.builtin.debug:
        msg: "Verification handled by testinfra configured in molecule.yml"
