---
- name: Configure Fedora server
  hosts: servers
  become: true
  gather_facts: true

  vars:
    is_server: true

  pre_tasks:
    - name: Print server information
      ansible.builtin.debug:
        msg: "Configuring server: {{ inventory_hostname }} ({{ ansible_host }})"

  roles:
    - role: base-system
